version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: always
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=False
    volumes:
      - /mnt/nas/ollama_models_work:/root/.ollama
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [ gpu ]

volumes:
  open-webui: